### ISSUE TITLE
How to use IExport generated by ts2fable?

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/ts2fable#116]
sorry for dumb question. But how to use Static type in above case. Means that is also abstract class. So, should I try createEmpty or jsoption for it. I tried jsoptions that did't work. need to check create empty though.

Below is simple reference code

```fsharp
type [<AllowNullLiteral>] IExports =
    abstract HelloResponse: HelloResponseStatic
    abstract Hello: HelloStatic

type [<AllowNullLiteral>] IReturn<'T> =
    abstract createResponse: unit -> 'T

type [<AllowNullLiteral>] IReturnVoid =
    abstract createResponse: unit -> unit

type [<AllowNullLiteral>] HelloResponse =
    abstract result: string with get, set

type [<AllowNullLiteral>] HelloResponseStatic =
    [<Emit "new $0($1...)">] abstract Create: unit -> HelloResponse

type [<AllowNullLiteral>] Hello =
    inherit IReturn<HelloResponse>
    abstract name: string with get, set
    abstract createResponse: unit -> unit
    abstract getTypeName: unit -> unit

type [<AllowNullLiteral>] HelloStatic =
    [<Emit "new $0($1...)">] abstract Create: unit -> Hello
```

So, how to create Hello out of HelloStatic?

PS: On side note. In Hello type createResponse type is coming wrong. It should be HelloResponse. For reference below is TypeScript code.

```ts
export interface IReturn<T>
{
    createResponse() : T;
}

export interface IReturnVoid
{
    createResponse() : void;
}

export class HelloResponse
{
    result: string;
}

// @Route("/hello")
// @Route("/hello/{Name}")
export class Hello implements IReturn<HelloResponse>
{
    name: string;
    createResponse() { return new HelloResponse(); }
    getTypeName() { return "Hello"; }
}
```

I am using latest 0.4 version of ts2fable. If you want I can file another issue for same.

cc/ @MangelMaxime

**Comment by kunjee17** [comment]
as requested by @ctaggart :)

**Comment by alfonsogarciacaro** [comment]
The bindings should expose an instance of the IExports object: [example](https://github.com/fable-compiler/fable-import/blob/7bb5576970d1533eb400b5ddcf712c6ed4bf62c0/Pg/Fable.Import.Pg.fs#L110-L111)

We don't have a convention yet for the name of the value. In the past it was `Globals`, there was a talk to use `Exports` from now on, but most of the times it's the same name as the module. This is probably fine, the only issue is many times the enclosing module has the same name which can be confusing to some users (in the sample `Fable.Import.Pg.Pg`), though we can fix that by adding an `AutoOpen` attribute on top:

```fsharp
open Fable.Import
// Now Fable.Import.Pg is open so we can use the value
Pg.Pool.Create()
```

**Comment by jgrund** [comment]
I may be missing something, but I am not seeing the `let` binding being generated and aliased to `IExports` in latest `ts2fable`

**Comment by kunjee17** [comment]
@jgrund it depends actually. If there is no global export then there will be no let binding . You have to create it by your self in that case. Else it will be generated.

**Comment by jgrund** [comment]
Yeah, was my mistake. I was missing the module wrapper around the declarations.
