### ISSUE TITLE
Types and Inheritage

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/ts2fable#12]
Hi! 
I'm making my way through the pixi bindings. 

But here I'm stuck on something like this:

```
module O = 
  module A =
     type AA = 
        member AAA: B.BB

  module B = 
    type BB =
      member BBB = A.AA
```

How can I manage such a situation? Thanks!

**Comment by alfonsogarciacaro** [comment]
Are you using `namespace rec XXX` on top of the file? ts2fable should do that now by default 🤔

**Comment by whitetigle** [comment]
Well with rec I could not make it work. That's why I removed it to see what was happening. I'm going to append it again and check 👍

**Comment by whitetigle** [comment]
In fact with `namespace rec Fable.Import.Pixi` , ionide does not show me any error but then I get lots of errors like the ones below in the console which seem to pop twice by the way 🤔

```
ERROR in ./src/pixi/App.fs
D:/workspace/samples-browser/src/pixi/Fable.Import.Pixi.fs(440,87): (440,101) error FSHARP: The type 'StencilManager' is not defined.
 @ ./src/pixi/Pixi.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/pixi/Pixi.fsproj

ERROR in ./src/pixi/App.fs
D:/workspace/samples-browser/src/pixi/Fable.Import.Pixi.fs(440,87): (440,101) error FSHARP: The type 'StencilManager' is not defined.
 @ ./src/pixi/Pixi.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/pixi/Pixi.fsproj

ERROR in ./src/pixi/App.fs
D:/workspace/samples-browser/src/pixi/Fable.Import.Pixi.fs(441,42): (441,56) error FSHARP: The type 'ObjectRenderer' is not defined. Maybe you want one of the following:
   ObjectConstructor
   Object
   ObjectURLOptions
 @ ./src/pixi/Pixi.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/pixi/Pixi.fsproj

ERROR in ./src/pixi/App.fs
D:/workspace/samples-browser/src/pixi/Fable.Import.Pixi.fs(441,42): (441,56) error FSHARP: The type 'ObjectRenderer' is not defined. Maybe you want one of the following:
   ObjectConstructor
   Object
   ObjectURLOptions
 @ ./src/pixi/Pixi.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/pixi/Pixi.fsproj
```

**Comment by alfonsogarciacaro** [comment]
@whitetigle Can you upload the file you're working on so I have a look?

**Comment by whitetigle** [comment]
Ok got some progress after tweaking the files with and without `namespace rec`...

![image](https://user-images.githubusercontent.com/883207/30932764-c0818218-a3c8-11e7-973e-c44e6fe04d00.png)

Something's displayed on screen ;)

**Comment by whitetigle** [comment]
@alfonsogarciacaro it seems to work now. 
Although I have some unrecognized modules by webpack (will play Sherlock to see what's happening). 
I will try to make my way through the official samples like I did previously with 3.x.x 👍

**Comment by whitetigle** [comment]
![pixiv4](https://user-images.githubusercontent.com/883207/30934051-9dc68e72-a3cc-11e7-9ad7-4ed38dc22107.gif)

ok doing some progress here with the new API. First sample's working👍 

```f#
module Pixi

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import
open Fable.Import.Pixi
open Fable.Import.Browser
open Fable.Import.JS

// create a new Sprite from an image path
let app = PIXI.Application(800., 600.)
Browser.document.body.appendChild(app.view) |> ignore

// create a new Sprite from an image path
let bunny = PIXI.Sprite.fromImage("bunny.png")

let renderer : PIXI.WebGLRenderer = !!app.renderer

// center the sprite's anchor point
bunny.anchor.set(0.5)
bunny.x <- renderer.width * 0.5
bunny.y <- renderer.height * 0.5

app.stage.addChild(bunny) |> ignore

let tick delta =
  // just for fun, let's rotate mr rabbit a little
  // delta is 1 if running at 100% performance
  // creates frame-independent tranformation
  bunny.rotation <- bunny.rotation + 0.1 * delta

// Listen for animate update
app.ticker.add(Func<_,_>tick) |> ignore
```

Ok I will close this issue now :)

**Comment by whitetigle** [comment]
Asking myself...  

`app.ticker.add(!!tick)`

or 

`app.ticker.add(Func<_,_>tick) `

**Comment by alfonsogarciacaro** [comment]
ts2fable is still using `Func` but with latest Fable we don't need it, normal functions are enough. Ideally we should try to avoid dynamic casting (`!!` or `unbox`) as much as possible with typed libraries. Until ts2fable is fixed (I know, I know..., it'll happen soon) you can change the signature of `add` manually to something like `f: (float->unit) -> unit`.

**Comment by whitetigle** [comment]
ok. I will do that! Thanks!
