### ISSUE TITLE
invalid & unused imports in Node.fs

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#139]
ts2fable@0.5.1
The generated Node.fs files generate these invalid imports and it blows up at runtime even though they are to be used. Several issues. What can we do?
``` fs
let [<Import("*","setTimeout")>] setTimeout: SetTimeout.IExports = jsNative
let [<Import("*","setImmediate")>] setImmediate: SetImmediate.IExports = jsNative
let [<Import("*","NodeJS")>] nodeJS: NodeJS.IExports = jsNative
let [<Import("*","_debugger")>] _debugger: _debugger.IExports = jsNative
```

**Comment by ctaggart** [comment]
Also, importing some unncessary packages leads to the warnings:
```
C:\Users\camer\tmp\myyargs2> .\start.ps1 -f .\.gitattributes
(node:15024) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:15024) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:15024) ExperimentalWarning: The http2 module is an experimental API.
1
```

**Comment by ctaggart** [comment]
These two throw warnings:
``` fs
let [<Import("*","crypto")>] crypto: Crypto.IExports = jsNative
let [<Import("*","http2")>] http2: Http2.IExports = jsNative
```

**Comment by alfonsogarciacaro** [comment]
Hmm, but they should be only _actually_ imported if they're _actually_ used 🤔 How are you referencing the bindings? By .dll or by file? In the second case is true the imports could happen always (because F#/Fable will try to expose `http2` from that file). One solution could be to force users to do the import explicitly like:

```fsharp
// This happen on top of the user's code

let http2: Http2.IExports = importAll "http2"
```

This forces the user to remember the Node module name and type the object appropriately. Another solution could be to expose an **inline** function instead of a value:

```fsharp
// This is in the bindings file, but as the function is inline the generated
// code will be in the user's file

let inline importHttp2(): Http2.IExports = importAll "http2"
```

**Comment by alfonsogarciacaro** [comment]
Sorry, I just realized the last suggestion is not a good fit for bindings which shouldn't contain actual code. The following should have the same effect and work from a .dll (without AST parsing/JS compilation):

```fsharp
[<Import("*", from="http2")>]
let importHttp2(): Http2.IExports = jsNative
```

So the trick is to make it a function instead of value to delay importing until the user calls the function.

**Comment by ctaggart** [comment]
> So the trick is to make it a function instead of value to delay importing until the user calls the function.
I did a quick check of that today, but didn't have luck when I tried. I will try again another day. Taking a break for a little bit.

**Comment by ctaggart** [comment]
@alfonsogarciacaro I tested this just now. It fails with or without making it a function. Starting from my template with `dotnet new http2 -n myhttp2`, then uncomment in `Node.fs`:
``` fs
let [<Import("*","setTimeout")>] setTimeout: SetTimeout.IExports = jsNative
```
or as a function:
``` fs
let [<Import("*","setTimeout")>] setTimeout(): SetTimeout.IExports = jsNative
```
I get the same error. As a function, I get this error:
```
Error: Cannot find module 'setTimeout'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\camer\tmp\myhttp2\dist\Node.js:8:19)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```
Looking at Node.js, it has:
``` js
var _setTimeout = require("setTimeout");

var setTimeout_2 = _interopRequireWildcard(_setTimeout);

const setTimeout = exports.setTimeout = setTimeout_2;
```

**Comment by ctaggart** [comment]
In the case of invalid imports being created, it looks like `declare namespace`should not end up being an import.

![image](https://user-images.githubusercontent.com/80104/33530679-2b143184-d862-11e7-9233-157b75815bcc.png)

**Comment by alfonsogarciacaro** [comment]
Sorry @ctaggart, I missed the notification 😓 Hmm, I think `declare` is the way to make something globally available in TS, so importing may not be necessary. It's possible that `Global` works:

```fsharp
let [<Global>] setTimeout: SetTimeout.IExports = jsNative
```

Anyway, those `__promisify__` functions don't look like a public API. It may be safe to ignore them.

**Comment by ctaggart** [comment]
For this particular case, the first 3 are taken of by https://github.com/fable-compiler/ts2fable/pull/141 once I get it working. And the last one, `_debugger` should be removed from the TypeScript definition. It was an undocumented API that was removed a couple of versions ago.

**Comment by ctaggart** [comment]
#141 removed the first three. Updating the invalid TypeScript definition is the only way to fix the last one. I opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21994 for that, but popular definitions seem to take a while to get merged.
