### ISSUE TITLE
Generated fs file should have System.Array instead of JS.Array

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/ts2fable#140]
In most cases where array is getting return. It is generated ResizeArray. that is good only. But I guess we should be having either list or F#.Array instead of JS.Array.

As in current state JS.Array is there as interface only. Can't create the same. So, it would be good that we don't create it for definition also. Instead we can always go for F# array or list. That would make this way more easier to consume or manipulate

**Comment by ctaggart** [comment]
The generated code for a while was been `ResizeArray`. 
https://github.com/fable-compiler/ts2fable-exports/blob/dev/Chai.fs
