### ISSUE TITLE
Reference types

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/ts2fable#146]
Hi! I'm just trying to create bindings for [PouchDB](https://pouchdb.com/).
So I went on [DefinitelyTyped ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/30957ad3d8a7bedfc3960f6921a336ebee25bed8/types/pouchdb-browser/index.d.ts)and there I found this:

```ts
/// <reference types="pouchdb-core" />
/// <reference types="pouchdb-adapter-idb" />
/// <reference types="pouchdb-adapter-websql" />
/// <reference types="pouchdb-adapter-http" />
/// <reference types="pouchdb-mapreduce" />
/// <reference types="pouchdb-replication" />
declare const PouchDb: PouchDB.Static;
export = PouchDb;
```

My question is simple: what's the best strategy to create bindings from this kind of file? Download all files individually and feed them to ts2fable?

Thanks!

**Comment by alfonsogarciacaro** [comment]
I'm not sure of the current status but @ctaggart has done great job to import multiple TS bindings directly. However, this case seems to be complicated because the declaration doesn't use `import` but the old `reference` tags. Not sure if it will work, you may need to translate each package individually 🤔

**Comment by whitetigle** [comment]
ok. I'll try both and tell here what happened. 👍

**Comment by whitetigle** [comment]
command `ts2fable.cmd pouchdb-core.d.ts pouchdb-adapter-http.d.ts pouchdb-idb.d.ts pouchdb-websql.d.ts pouchdb-mapreduce.d.ts pouchdb-replication.d.ts > Fable.Import.PouchDB.Core.fs`

seems to take only first file `pouchdb-core.d.ts`. Is there a sample anywhere to include multiple files?

**Comment by whitetigle** [comment]
Another problem I ran into is that large portions of codes missing in the generated bindings. Like [this part](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/30957ad3d8a7bedfc3960f6921a336ebee25bed8/types/pouchdb-core/index.d.ts#L591).

All the contents for `interface Database<Content extends {} = {}>  {...}` result in and [

```f#
<AllowNullLiteral>] Database<'Content> =
    interface end
```
So I think I'd better start manually from here.

**Comment by whitetigle** [comment]
Well, at least ts2fable has allowed me to get all the types for the zounds options PouchDb has.
I just have to make my way thought the Database object. So it's ok. 😄

**Comment by whitetigle** [comment]
I just tried to make this more clear here: https://github.com/fable-compiler/ts2fable/issues/147
