### ISSUE TITLE
Question: collate different sources

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/ts2fable#147]
Hi!
I'm currently working on PouchDB wrappers. But my currrent knowledge on both Typescript and F# limits what I can do.

My current issue is that I have types for PouchDB that are registered like this in an [index.d.ts file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pouchdb/index.d.ts):

```ts
/// <reference types='pouchdb-adapter-fruitdown' />
/// <reference types='pouchdb-adapter-http' />
/// <reference types='pouchdb-adapter-idb' />
/// <reference types='pouchdb-adapter-leveldb' />
/// <reference types='pouchdb-adapter-localstorage' />
/// <reference types='pouchdb-adapter-memory' />
/// <reference types='pouchdb-adapter-node-websql' />
/// <reference types='pouchdb-adapter-websql' />
/// <reference types='pouchdb-browser' />
/// <reference types='pouchdb-core' />
/// <reference types='pouchdb-http' />
/// <reference types='pouchdb-mapreduce' />
/// <reference types='pouchdb-node' />
/// <reference types='pouchdb-replication' />
declare const plugin: PouchDB.Static;
export = plugin;
```

So as you can see, pouchdb seems to have many sub-repositories. 

I got every d.ts file and tried to export them to F# using ts2fable.
However, there is a Database typescript inteface that is updated from many files. So that in the end we've got this big database interface merged from all these sources. (that is, if I understand well the process)

`interface Database<Content extends {} = {}> {...}`

The same thing goes with PouchDB plugins which updates this Database interface as well. For instance the pouchd-find plugin adds a find method to the interface.

So currently here's my process:

1. I export every ts file individually 
2. I copy and paste the code into my Fable.Import.PouchDB.fs file 
3. I manually merge the Database interface 

There's another element in charge here: the Database interface is never actually transpiled to F#. 

This thing:

```ts
    interface Database<Content extends {} = {}> {
        viewCleanup(callback: Core.Callback<Core.BasicResponse>): void;

        viewCleanup(): Promise<Core.BasicResponse>;

        query<Result, Model = Content>(fun: string | Map<Model, Result> | Filter<Model, Result>, opts: Query.Options<Model, Result>, callback: Core.Callback<Query.Response<Result>>): void;

        query<Result, Model = Content>(fun: string | Map<Model, Result> | Filter<Model, Result>, callback: Core.Callback<Query.Response<Result>>): void;

        query<Result, Model = Content>(fun: string | Map<Model, Result> | Filter<Model, Result>, opts?: Query.Options<Model, Result>): Promise<Query.Response<Result>>;
    }

```

becomes:

```f#
    type [<AllowNullLiteral>] Database<'Content> =
        interface end
```

But let's say that eventually this will work. Will I be able to just merge the Database interface automatically? Is it already possible?

**Comment by alfonsogarciacaro** [comment]
Hmm, I hadn't seen a TypeScript interface split in several files before, so I cannot say... Maybe using F# type exceptions? Though to be honest, I don't know right now how they work with imported types 🤔

**Comment by ctaggart** [comment]
I think issue #128 and pr #145 are related. When I get back to ts2fable development, reviewing that pr and these use cases is on my todo list.

**Comment by ctaggart** [comment]
This should be solved by #216. You can try it out with `yarn global add ts2fable@next`. You will need to use the `--export` option.

**Comment by whitetigle** [comment]
ok here are the results of my first tests:


`Unexpected identifier`: Not compacted
```
        type [<StringEnum>] [<RequireQualifiedAccess>] Availability =
            | Available
            | Compacted
            | Not compacted
            | Missing
```

ts source: 
        `type Availability = 'available' | 'compacted' | 'not compacted' | 'missing';`

**Comment by ctaggart** [comment]
That looks like a bug in string enum. if you comment out `| Not compacted`, how does the rest of it look?

**Comment by whitetigle** [comment]
I'm working on it step by step 😉 

So I replaced `Not compacted `with `NotCompacted `

- Then I got this error: `Blob is not defined:`
`U3<string, Blob, Buffer>`

- There's an unknown type here (Debug):
`abstract debug: Debug.IDebug with get, set`

- We're missing some context for the pouchDb Core module:
![image](https://user-images.githubusercontent.com/883207/37978131-9e03b0ac-31e5-11e8-9f63-4d4ecbaf1d3a.png)
So it's looking for `Microsoft.FSharp.Core` instead

I'm looking right now at the other errors, I'll make a new report later

**Comment by whitetigle** [comment]
I also have this:

```f#
module PouchDB =

    type [<AllowNullLiteral>] IExports =
        abstract : StaticStatic
```

![image](https://user-images.githubusercontent.com/883207/37979614-5289bab4-31e9-11e8-93e6-9e080d18d460.png)

**Comment by whitetigle** [comment]
the module PouchDB.Core seems to be written many times (4 times):
![image](https://user-images.githubusercontent.com/883207/37979708-97dfd9f4-31e9-11e8-89c6-b979d4f61e07.png)

And the module PouchDB is written 11 times. So can it be some redefinitions in ts submodules not handled correcty?
