### ISSUE TITLE
The type ResizeArray is not an interface type

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#15]
Follow instructions in #14 to reproduce the issue:

```
ts2fable .\node_modules\@types\google-protobuf\index.d.ts > .\FableApp\src\google-protobuf.fs
```

compile error is [here](https://github.com/ctaggart/grpc-web/blob/d11754b302daf0e90d6971d01e8e2f31a6f26e2a/example/FableApp/src/google-protobuf.fs#L22-L23):
``` fsharp
and [<AllowNullLiteral>] FieldValueArray =
    inherit ResizeArray<FieldValue>
```

![image](https://user-images.githubusercontent.com/80104/31457019-6ca27256-aeb3-11e7-9c04-bc0ba135b82d.png)

generated from [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-protobuf/index.d.ts#L6-L10):
``` ts
interface FieldValueArray extends Array<FieldValue> {} // tslint:disable-line no-empty-interface
```

**Comment by ctaggart** [comment]
I can change the F# code to a type abbreviation to make it compile, but I'm not sure this is correct:
``` fs
and FieldValueArray =
    ResizeArray<FieldValue>
```

**Comment by alfonsogarciacaro** [comment]
Yeah, ResizeArray gives me many headaches. In theory it's the best option to translate JS Array, but many times it's more convenient to use the F# array syntax. Besides that, FunScript used `IList` to translate JS array, I don't remember exactly why I picked ResizeArray instead :thinking:

About inheriting in general, one of the proposals for the ts2fable rewrite is to use only interfaces and not classes (last point in [this comment](https://github.com/fable-compiler/ts2fable/issues/1#issue-217374509)) to avoid these problems, as in TS it's even possible that an interface inherits from a class. This is not totally ideal though, as sometimes the user may need to inherit from a JS class (as with `React.Component`).

**Comment by ctaggart** [comment]
I am now about the google-protobuf definition without issue. This particular example gets mapped as:
``` fs
type [<AllowNullLiteral>] FieldValueArray =
    inherit Array<FieldValue>
```
