### ISSUE TITLE
Add  FsFile Tests?

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#155]
If i want to add below test sample , mocha has to reference ts2fable.fs to invoke transform method

But the yargs code in ts2fable.fs will trigger the exception of "Please provide the path to a TypeScript file".

So the #156 **rearranges** a lot of codes which i think is more logical

**Benifits of using this feature:**

**1.** 
Chalk.fs has below error 
```fsharp
let [<Import("*","types")>] chalk: obj = jsNative
```
"types" is error , true path is "chalk". 

now we can assert that if FsVariable's Path is "chalk" or not

**2.** 
we can debug & test code in testFiles directly with  the core of the repository --- transform method

Sorry for my poor English.

**Comment by humhei** [comment]
For Example , my lasted pull request #153 can test like below
```fsharp 
describe "transForm Test" <| fun _ ->

    //https://github.com/fable-compiler/ts2fable/issues/154
    it "Duplicated Variable Exports Test" <| fun _ ->
        fsFiles
        |> List.head
        |> fun f ->  f.Modules
        |> List.head
        |> fun md -> md.Types
        |> List.choose FsType.asVariable 
        |> fun vbs -> 
            if vbs.IsEmpty then ()
            else 
                vbs
                |> List.groupBy(fun vb -> vb.Name)
                |> List.length
                |> equal 1
```

**Comment by humhei** [comment]
The point is that the pr change a lot files
I don't known it is deserved

**Comment by alfonsogarciacaro** [comment]
Fantastic work @humhei, thanks a lot! Adding tests will make the tool much more robust and it's another step further to fully automatize binding generation from Typescript declaration packages :clap: :clap: I agree that it should be possible to reference ts2fable.fs directly for the test without calling it from the CLI.

I'll let @ctaggart review #156 as he knows the code base much better than me now, but please tell me if you need anything.

By the way, don't worry about your English. It's perfectly understandable and most of us aren't native either 😃
