### ISSUE TITLE
`undefined` in many types

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#16]
Are the `undefined`s supposed to be `option`s instead?

When I run:
```
ts2fable .\node_modules\@types\google-protobuf\index.d.ts > .\FableApp\src\google-protobuf.fs
```

It imports a lot of `undefined`s that end up not compiling.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-protobuf/index.d.ts#L14
``` ts
getJsPbMessageId(): (string | undefined);
```

becomes
https://github.com/ctaggart/grpc-web/blob/d11754b302daf0e90d6971d01e8e2f31a6f26e2a/example/FableApp/src/google-protobuf.fs#L30
``` fs
member __.getJsPbMessageId(): U2<string, undefined> = jsNative
```

Although this error message has a point, I want things to compile:
![image](https://user-images.githubusercontent.com/80104/31459420-095017e6-aebb-11e7-8bdb-98aa52306444.png)

**Comment by et1975** [comment]
Hm, not sure how Fable treats `undefined` at runtime, but if you just want things to compile you could replace all `U2<_,undefined>` with `_ option`.

**Comment by alfonsogarciacaro** [comment]
Yes, `option` could be a good option here (you see what I just did, right? :wink:). Fable compiles `None` and `unit` as null, and when comparing with null it always use non-strict JS equality (`x == null`) which would eval to true both for `null` and `undefined`.

So in practice Fable doesn't make any distinction between F# None/unit/null and JS null/undefined.

**Comment by ctaggart** [comment]
As of #19 in the `develop` branch, unions with `null` or `undefined` are turned into F# options.
