### ISSUE TITLE
Generated fs files should have EventListener instead of Func<Event, obj>

### ISSUE THREAD

**Issue by JohnStov** [fable-compiler/ts2fable#160]
I'm trying to tidy up the WebAudio part of `Fable.Import.Browser`, and it looks like everywhere the typescript contains an event handler in the form `(ev: Event) => any`, ts2fable converts this to a `Func<Event, obj>`.

This makes it hard to write event handler functions, because you always have to return an `obj` to satisfy the type validaton, although you know the caller is going to discard it.

There is already an `EventListener` with a type of `Func<Event, unit>` which would probably be a better fit.

**Comment by alfonsogarciacaro** [comment]
In latest Fable.Import.Browser we use `Event->'Out` so the compiler doesn't complain if you don't return anything. If we're sure that in most cases users won't return anything we can just use `Event->unit` indeed.

**Comment by JohnStov** [comment]
In that case, I'll use `Event -> 'Out` for my changes in `Fable.Import.Browser`, then the rest will eventually catch up.
