### ISSUE TITLE
switch to webpack+fable-loader & fake5

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#162]
- [x] https://github.com/fable-compiler/Fable/issues/1240
Using **webpack+fable-loader** to replace **fable-splitter**?
~~This will enable HMR and escape `ERROR: The process cannot access the file`~~
As https://github.com/ionide/ionide-vscode-fsharp done
- [x]  Using **fake5** to replace **powershell** scripts?
It is more friendly for f# programmer

**Comment by alfonsogarciacaro** [comment]
I'd be very happy to use fake5 as I don't have powershell installed on my system. About Webpack, I think HMR is designed for the browser, I'm not sure if it can be used in a Node app 🤔

**Comment by humhei** [comment]
![image](https://github.com/humhei/hello/blob/master/hello.gif)

**Comment by humhei** [comment]
**Update:**
We should keep a eye on https://github.com/ionide/ionide-vscode-fsharp
As it is a fable node app too
😄
