### ISSUE TITLE
Extract type literal from type alias

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#185]
```typescript
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
```
### Compiled fsfile
```fsharp
type EventHandler<'E> =
    obj
```
This will case error: `This construct is deprecated: This type abbreviation has one or more declared type parameters that do not appear in the type being abbreviated. Type abbreviations must use all declared type parameters in the type being abbreviated. Consider removing one or more type parameters, or use a concrete type definition that wraps an underlying type, such as 'type C<'a> = C of ...'.`
### My preference
```fsharp
type [<AllowNullLiteral>] EventHandler<'E> =
    abstract bivarianceHack: ``event``: 'E -> unit
```

**Comment by ctaggart** [comment]
Nice work @humhei

**Comment by wenisy** [comment]
Hi @humhei ,
I'm a little confused about `bivarianceHack`

` { bivarianceHack(event: E): void }["bivarianceHack"];`

does it be equivalent to `(event: E): void` ? If so why do we use this workaround?

**Comment by humhei** [comment]
I am not familiar with typescript 😓 

I just adapt the workaround from here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L679
