### ISSUE TITLE
How does AppVeyor know which definitions to export to ts2fable-exports ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/ts2fable#186]

**Comment by humhei** [comment]
Commit strategy
When PR is merged. Commits will be added to master branch
When PR is not merged. Commits will be added to dev branch
`APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME` will be empty when PR is not merged
I use it to judge whether to send master branch or dev branch

**Comment by MangelMaxime** [comment]
What I mean, is how do the repo know it's need to generate types for:

- VSCode.fs
- IziToast.fs
- Electron.fs
- etc.

**Comment by humhei** [comment]
Sorry 😄 
### Two ways:
- **before**: in `ts2fable.fs` yargs cli code generation
for example:    `writeFile ["node_modules/@types/node/index.d.ts"] "test-compile/Node.fs"`

- **now**: in `fsFileTest.fs` 
generate `definition` every test

**Comment by humhei** [comment]
I use `fsFileTest.fs` to debug most code
using `mocha only` to debug single test

**Comment by MangelMaxime** [comment]
Ah so if we would to generate a new version of `VSCode.fs`, we would need to update the version in the package.json [here](https://github.com/fable-compiler/ts2fable/blob/ba00ae508572c5771cc98e5f62aac7b94a710554/package.json#L55) ?

**Comment by humhei** [comment]
Yes

**Comment by MangelMaxime** [comment]
Hum ok, I think we need to document this point somewhere.

I will see when I have sometime.

Thanks for the answer :)
