### ISSUE TITLE
following exports from index.d.ts eg in office-fabric-ui-react #740

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/ts2fable#2]
Follow up of https://github.com/fable-compiler/Fable/issues/740

**Comment by ctaggart** [comment]
I did look at this yesterday. office-ui-fabric-react has a major/major dependency tree. This project needs some work on:
- [ ] automatic namespace
- [ ] manual namespace
- [ ] helping import
```
yarn add office-ui-fabric-react --dev
```

**Comment by ctaggart** [comment]
This was solved by #216. You can try it out with `yarn global add ts2fable@next`. There are other issues with the office imports, but this is a step forward.
