### ISSUE TITLE
Update react & reactxp version broke master

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#203]
@humhei please use pull requests instead of pushing directly to master branch to avoid breaking it:
https://github.com/fable-compiler/ts2fable/commits/master
![image](https://user-images.githubusercontent.com/80104/37690952-64707ba4-2c7c-11e8-9e0d-8fd93d3bdc41.png)

**Comment by humhei** [comment]
Thanks for the tip.
But for this ci breaking 
I will fix it as soon as possible

**Comment by humhei** [comment]
I think it was broke by    
 <Compile Include="React.fs" />

**Comment by ctaggart** [comment]
I recommend reverting that commit and then creating a pull request for the changes.
