### ISSUE TITLE
Add yargs option to support importing from multiple linked tsfiles

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#207]
https://github.com/fable-compiler/ts2fable-exports/commit/8f6b6148cdd9d1bb24a07164e6143788f3c457db
`office-ui-fabric-react` generated an almost empty file

I want to embed `multiple` option to `yargs` .
It has description `Import from multiple linked tsfiles`
Arguments are a entry `tsfile` and a output `fsfile`

This is a beginning to get `office-ui-fabric-react` worked

For example:
`ts2fable --multiple node_modules/office-ui-fabric-react/lib/index.d.ts
test-compile/OfficeUiFabricReact.fs`
![imgr](https://github.com/humhei/Resources/blob/Resources/yargs.png?raw=true)

**Comment by ctaggart** [comment]
`--multiple` is not needed. The command line simply filters based on the extension:
https://github.com/fable-compiler/ts2fable/blob/master/src/ts2fable.fs#L24
``` fs
let tsfiles = files |> List.filter (fun s -> s.EndsWith ".ts")
```

**Comment by humhei** [comment]
`node_modules/office-ui-fabric-react/lib/index.d.ts
` is a entry file
Then we should resolve all related tsfiles by `typescript compile api`
If we add this yargs option. 
Should we cancel inputting multiple `tsfiles`?
Only one `tsfile` is needed

**Comment by humhei** [comment]
In other words
Two options
- Yargs: entry file + `multiple option` = multiple files input (by `typescript compile api` resloving `entry tsfile`) （I think `office-ui-fabric-react` should use this,As too many input files which we can using  `typescript compile api` find them easily）
- Yargs: manual multiple input files

**Comment by humhei** [comment]
```fsharp
        ts2fable
            [   "node_modules/@types/google-protobuf/index.d.ts"
                "node_modules/@types/google-protobuf/google/protobuf/empty_pb.d.ts"
                "test-compile/Protobuf.fs"
            ]
```
This lines should be replaced by 
```fsharp
        ts2fable
            [ "--multiple"
              "node_modules/@types/google-protobuf/index.d.ts"
               "test-compile/Protobuf.fs"
            ]
```
But i don't understand the logical connection between 
`"node_modules/@types/google-protobuf/index.d.ts"`
and `"node_modules/@types/google-protobuf/google/protobuf/empty_pb.d.ts"`
So i will annotate them

**Comment by humhei** [comment]
If i express my intention badly.(my English is not very well)
Please ask me in detail @ctaggart

**Comment by ctaggart** [comment]
I think we are missing something. I'm going to try to explain now with some code.

**Comment by ctaggart** [comment]
#216 fixes this
