### ISSUE TITLE
map imports

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#21]
#19 now in the `develop` branch left a couple of items left for imports. It was clarified what should be done in [this comment](https://github.com/fable-compiler/Fable/issues/1200#issuecomment-339471153):
> About importAll, it's better to avoid that because it's an expression and bindings should avoid actual code. I'd recommend using the attribute version instead:
``` fs
[<Import("*", "IziToast")>]
let IziToast: IExports = jsNative
```
> The best reference for the bindings is the latest Fable.Import.Node written by @jgrund as we were deciding the new standards when creating them, like using an interface named IExports for the exposed members instead of the old Globals and then making it available using a public module value with the Import attribute as shown above ☝️

- map export statements #28 
- map global variables

**Comment by ctaggart** [comment]
The export statements are now mapped. For typescript.d.ts, the 
``` ts
export = ts;
```
results in
``` fs
let [<Import("*","typescript")>] ts: ts.IExports = jsNative
```

Now, I just need to figure out when to map variables to imports. Guessing it has to do with the `declare` keyword.
``` ts
declare var iziToast: IziToast
```
Currently ends up as:
``` fs
type IExports =
    member __.iziToast with get(): IziToast = jsNative and set(v: IziToast): unit = jsNative
```
but should be
``` fs
let [<Import("*","iziToast")>] iziToast: IziToast = jsNative
```

**Comment by ctaggart** [comment]
, can you let me know if this works where the namespace is lowercase. If case matters, where should it be taken from? I'm currently using the izitoast.d.ts file.

``` ts
let [<Import("*","izitoast")>] iziToast: IziToast = jsNative
```

**Comment by ctaggart** [comment]
This is done unless the case matters or other bugs.

**Comment by kunjee17** [comment]
@ctaggart which part you liked me to check ?

**Comment by ctaggart** [comment]
@kunjee17, this being lowercase: `"izitoast"`

**Comment by kunjee17** [comment]
I m having this line in code `let [<Import("*","iziToast")>] iziToast: IziToast = jsNative` and it works without any issue.

**Comment by ctaggart** [comment]
@kunjee17, but what happens if you change it to a lowecase `t`?
``` ts
let [<Import("*","izitoast")>] iziToast: IziToast = jsNative
```

**Comment by kunjee17** [comment]
@ctaggart it works at least for me. :)

**Comment by alfonsogarciacaro** [comment]
@ctaggart Great work, as always! About the case, it does matter (although you can declare import aliases in Webpack, for example). Knowing where to get it is a bit tricky. When `Fable.Core.ImportAttribute` was designed, I think it was standard in TypeScript to do something like `declare module "izitoast"` while now (everything changes so quickly in TypeScript!) you put the declaration in an [index.d.ts file](https://github.com/dolce/iziToast/blob/f8cb88d5828a70f278608927e608b3fb2246fac6/types/index.d.ts#L291-L300) and the name of the package is supposedly taken from the package.json file in the same directory. I'm not sure how to do solve this, maybe we need to pass the name of the npm package to ts2fable in a command argument, or let ts2fable check if there's any package.json file next to .d.ts 🤔 

About `declare var iziToast: IziToast`, IIRC this is a global variable, you can represent in Fable as:

```fsharp
// If you omit the attribute argument, Fable will use
// the name of the F# value
[<Global("iziToast")>]
let iziToast: IziToast = jsNative
```

But in general, I wouldn't recommend exposing global variables. It's probably safe to ignore global TS declarations in most cases.

**Comment by ctaggart** [comment]
We'll have to address this after 0.3.0. Hopefully 0.4.0.

**Comment by ctaggart** [comment]
How to I get the moduleName for each SourceFile?
https://github.com/ajafff/tsutils/issues/14
