### ISSUE TITLE
string enum with period

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#219]
There are a few problems with code generated from .\node_modules\@types\react-native-fbsdk\index.d.ts. A string enum with a period isn't handled correctly. It doesn't compile:

![image](https://user-images.githubusercontent.com/80104/38372639-ed0b13c2-38b4-11e8-9211-e0545027cdf4.png)

This is from this snippet:
``` ts
export type Permissions = 'public_profile'
    | 'user_friends'
    | 'email'
    | 'user_about_me'
    | 'user_actions.books'
    | 'user_actions.fitness'
    | 'user_actions.music'
    | 'user_actions.news'
    | 'user_actions.video'
    | 'user_birthday'
    | 'user_education_history'
```

**Comment by nojaf** [comment]
Could be resolved by using `CompiledName` when enum entry has dots.

F.ex:
```fsharp
type Permissions = 
    | [<CompiledName('user_friends')>] User_friends
    | [<CompiledName('email')>] Email
    | [<CompiledName('user_about_me')>] User_about_me
    | [<CompiledName('user_actions.books')>] User_actions_books
    | [<CompiledName('user_actions.fitness')>] User_actions_fitness
    | [<CompiledName('user_actions.music')>] User_actions_music
    | [<CompiledName('user_actions.news')>] User_actions_news
    | [<CompiledName('user_actions.video')>] User_actions_video
    | [<CompiledName('user_birthday')>] User_birthday
    | [<CompiledName('user_education_history')>] User_education_history
```
Might be a safe thing to generate each time with `CompiledName` and sanitize the enum flag.

**Comment by alfonsogarciacaro** [comment]
Yes, that'd be the proper solution for StringEnums :+1:

**Comment by nojaf** [comment]
I'm guessing the fix is [somewhere around here](https://github.com/fable-compiler/ts2fable/blob/428b8ccf03817bd24277ed928a875d8de4aa0995/src/print.fs#L212)?

**Comment by alfonsogarciacaro** [comment]
Looks like so! I've lost touch with this code base but I'm sure @humhei would appreciate a PR! :)

**Comment by humhei** [comment]
I sended a PR for this issue #231 
I think the generated code should as follows
```fsharp
type [<StringEnum>] [<RequireQualifiedAccess>] Permissions =
    | Public_profile
    | User_friends
    | Email
    | User_about_me
    | [<CompiledName "user_actions.books">] User_actions_books
    | [<CompiledName "user_actions.fitness">] User_actions_fitness
    | [<CompiledName "user_actions.music">] User_actions_music
    | [<CompiledName "user_actions.news">] User_actions_news
    | [<CompiledName "user_actions.video">] User_actions_video
    | User_birthday
    | User_education_history

```
As [// by default Fable lowercases the first letter of the name for the value](https://github.com/humhei/ts2fable/blob/de492f5412b03e6e09cdc5a6256bbf45333979d8/src/naming.fs#L55)
   ` | Public_profile` will compiled to `pulbic_profile` automatically

**Comment by nojaf** [comment]
Could we have a release for this please?
