### ISSUE TITLE
Problems translating Babylon.js def file

### ISSUE THREAD

**Issue by darrix** [fable-compiler/ts2fable#220]
Hi, I'm having a problem generating a .fs file for the Babylon.js type definition file.  I'm seeing a fair number of type definition errors, frequently related to "Partial<>".  I'm also seeing a number of errors in the translation process with the message "unsupported printType None".  I've cloned ts2fable and will start there but I'm wondering if you have suggestions about translation issues you've seen before that might be a useful starting point?

**Comment by humhei** [comment]
Thanks for the reporting
I think this has been fixed in https://github.com/fable-compiler/ts2fable/issues/179
But we still didn't update the stable version of ts2fable 
You can try it with ts2fable@next or generate `Babylon.js` using source code

**Comment by darrix** [comment]
Hi, thanks--the @next version cleared up the Partial<> issues.  Still a few others to look into.  Thanks for your help.

**Comment by 0x53A** [comment]
hi @darrix, I'm currently trying to use ``react-babylonjs`` and also hitting a few issues. Have you got any further with ``Still a few others to look into``?

Thank you!
