### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#221]
@humhei When shall we release 0.6.0? People keep running into bugs with 0.5.2 that have been resolved like #220. Anything you wish to squeeze in before a release?

**Comment by humhei** [comment]
Thanks for the reminder!
I released it with 0.6.0
Please release the [npm package](https://www.npmjs.com/package/ts2fable) to 0.6.0 😄

**Comment by ctaggart** [comment]
It is not published. Looks like there are a couple of problems.

1. It looks like the automatic publishing to npmjs stopped working 19 days ago.
https://www.npmjs.com/package/ts2fable
![image](https://user-images.githubusercontent.com/80104/38762092-096a54fc-3f4e-11e8-8008-69cdf9b1829d.png)

2. The tag should have built a `0.6.0` version
https://ci.appveyor.com/project/fable-compiler/ts2fable/history
![image](https://user-images.githubusercontent.com/80104/38762115-462a6210-3f4e-11e8-923a-49e24e0b1a01.png)

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/38762356-a941ae70-3fbd-11e8-9eae-ba7aeb3c2286.png)
![image](https://user-images.githubusercontent.com/25994449/38762360-b2d5758e-3fbd-11e8-911f-b3fe759845e0.png)

**Comment by humhei** [comment]
It is strange 😕

**Comment by humhei** [comment]
This is a fake bug?
I tested it
Fake version rc004 taked this
But beta0013 didn't

**Comment by ctaggart** [comment]
@humhei your FAKE fixes in #223 worked. Go ahead and release 0.6.1 when you are ready. You can then promote it to `latest` by running `npm dist-tag add ts2fable@0.6.1 latest`.

**Comment by ctaggart** [comment]
Good job @humhei. If you have a twitter, you should announce it. I had to switch to TypeScript on my paid project, so ts2fable is your hands now.

**Comment by StachuDotNet** [comment]
@ctaggart I hope you know that the rest of us deeply appreciate the work you did with ts2fable. :)

**Comment by StachuDotNet** [comment]
And hopefully continue to do! But at an understandable distance. In the meantime, thanks @humhei for your efforts as well. Looking forward to seeing fable march forward with the help of this lovely tool.
