### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/ts2fable#233]
Add an online version of ts2fable, this would be helpful to copy and transform small module's tsd.

**Comment by alfonsogarciacaro** [comment]
That would be very nice. Maybe our expert in making Fable tools available online can have a look (I'm looking at you @MangelMaxime :wink:). @humhei Does ts2fable use any Node.js API besides file reading?

**Comment by humhei** [comment]
I considered  it before and thought it is viable 
There is not much Node.js API in ts2fable
And Typescript Compile API is also avalible in web side(highly possible)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Gnagnagna :p

Yes, I can easily make the layout/base for it. Like I did for HTML to Elmish. And then we just need to make ts2fable callable as a library and that's it.

I will prepare a PR for it.

**Comment by alfonsogarciacaro** [comment]
I don't want to put too much on your plate @MangelMaxime ;) Only if you've time after the other announcements :)

**Comment by MangelMaxime** [comment]
Other announcements 🤔 Ahah yes 🤐 

No worries :) I already have the code for this one so it will be easier to do :) I still need to specify the other one.

**Comment by humhei** [comment]
https://humhei.github.io/ts2fable/
http://fable.io/ts2fable
![image](https://user-images.githubusercontent.com/25994449/42741326-b989689e-88e3-11e8-8d8e-b5b61fb2e191.png)

**Comment by MangelMaxime** [comment]
@humhei Awesome work :)

I fixed the settings of the repository and it's now live: http://fable.io/ts2fable/

<img width="1920" alt="capture d ecran 2018-07-16 a 08 04 59" src="https://user-images.githubusercontent.com/4760796/42744750-f63c2264-88ce-11e8-9a43-85efcac511b7.png">

**Comment by humhei** [comment]
> Can we announce it in Twitter

I did it 😄

**Comment by humhei** [comment]
My ability of expression is a bit not clear.
You guys can retweet it 😺

**Comment by alfonsogarciacaro** [comment]
No worries! 😄 Thanks a lot for announcing it and all your work! 💪
