### ISSUE TITLE
Invalidated npm authentication

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#236]
![image](https://user-images.githubusercontent.com/25994449/42722945-5dc92c54-8787-11e8-97a3-2be244e4c9f9.png)

**Comment by MangelMaxime** [comment]
Yes, there was a virus introduce in [eslint-scope](https://github.com/eslint/eslint-scope/issues/39) which is used by `webpack` and so for safety npm revoked all the access tokens.

We need to generate another npm token. I think @ctaggart is the person that did it the first time.

**Comment by humhei** [comment]
@alfonsogarciacaro 
![image](https://user-images.githubusercontent.com/25994449/42994364-7b67ab10-8c40-11e8-9ccf-7bfd941b4294.png)
Are you able to  generate another npm token.
It seems @ctaggart didn't notice this message or busy with other things 😄

**Comment by alfonsogarciacaro** [comment]
@humhei TBH it was @ctaggart who did all the work so I'm not sure how to add the token. Maybe I can add you as maintainer of ts2fable package so you can do it yourself? Do you have an npm username?

**Comment by MangelMaxime** [comment]
@humhei Yes this is need in order to not make the token available from Source code.
It should be configured from the CI interface.

**Comment by ctaggart** [comment]
Right, @humhei just replace the `npmauthtokent` environment variable in AppVeyor.

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/43031861-10e4d7ca-8cdd-11e8-9171-97cd4d485519.png)
So i have the right to config environments now?

**Comment by alfonsogarciacaro** [comment]
Thanks @ctaggart I updated the npm token in the appveyor config :) I also added you as maintainer to the ts2fable npm package @humhei :+1: Thanks a lot for all your work!

**Comment by MangelMaxime** [comment]
@humhei @alfonsogarciacaro 

Are we sure the new token has been set correctly? See #261
