### ISSUE TITLE
import Fable.Import.Browser in case of HTMLElement

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#26]
As suggested by @kunjee17 in [this comment](https://github.com/fable-compiler/Fable/issues/1200#issuecomment-339333246).

**Comment by MangelMaxime** [comment]
In some application opening `Fable.Import.Browser` overwrite some of the feature modules/class/etc.

For example, if you open `Fable.Import.Browser` you can't access anymore the `Event` type from F#. You will get the event browser type instead.

For this reason, in my application I prefer to open `Fable.Import` and use : `Browser.HTMLElement` etc. for example.

Perhaps this is not dangerous for the import I don't know.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime opening a module only affects the code below the open statement **int the same file** so this shouldn't affect user code :)

**Comment by MangelMaxime** [comment]
Yes that's true and binding don't include code so that's fine indeed :)

**Comment by ctaggart** [comment]
Fixed by #34. Currently just looking for types that StartWith `HTML`. That works for the izitoast.d.ts test case. May be in the future we can make it more robust by seeing if the type is derived from `HTMLElement` using the TypeChecker.
