### ISSUE TITLE
Appveyor CI failing

### ISSUE THREAD

**Issue by fbehrens** [fable-compiler/ts2fable#261]
seems to be an issue with the `\n` in `..\\node...` interpreted as `newline`
see https://ci.appveyor.com/project/fable-compiler/ts2fable/build/0.6.1-build.348#L408
```
warning Error running install script for optional dependency: "C:\\projects\\ts2fable\
ode_modules\\v8-profiler: Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c node-pre-gyp install --fallback-to-build
Directory: C:\\projects\\ts2fable\
ode_modules\\v8-profiler
Output:
```

**Comment by MangelMaxime** [comment]
This isn't the reason of the CLI failing. 
What you see on the line you pointed is just AppVeyor display IMO.

If this was the failing line then FAKE would have stopped here and return.

The failing target is: `Target 'Cli.Publish' failed.`

**Comment by fbehrens** [comment]
Yepp, i draw wrong conclusion from the output. Above lines are not from last CI build.
The errror from the last [build](https://ci.appveyor.com/project/fable-compiler/ts2fable/build/0.6.1-build.383#L599) is

    -> BuildFailedException: Target 'YarnInstall' failed

**Comment by humhei** [comment]
Already worked 😄 
![image](https://user-images.githubusercontent.com/25994449/44908067-b0caca80-ad4c-11e8-85fb-341fd1bb5a60.png)

**Comment by MangelMaxime** [comment]
@humhei Thanks

Why are we having these lines in the `WebApp.Publish` ?

https://github.com/fable-compiler/ts2fable/blob/master/common.fsx#L357-L360

IMO `WebApp.Publish` should just be:

```fs

Target.create "WebApp.Publish" (fun _ ->
    if (isAppveyor) then
            Yarn.exec "run gh-pages --dist web-app/output" id
)
```

There is nothing more needed to publish the WebApp to `gh-pages`. It is not related to npm or git.

**Comment by humhei** [comment]
Yeah,
You are right.
I just do not take the chance to delete it 
```
Target.create "WebApp.Publish" (fun _ ->
    if (isAppveyor) then
            Yarn.exec "run gh-pages --dist web-app/output" id
)
```
Actually ,The codes should all be deleted.
Because we publish online version manually now

**Comment by MangelMaxime** [comment]
I would still prefer to auto publish the web app :)

So we know that the web app is always using latest version of ts2fable. If you agree, I can send a PR to fix the `WebApp.Publish` target.
