### ISSUE TITLE
Update ts2fable online version automaticlly when commit is merged

### ISSUE THREAD

**Issue by humhei** [fable-compiler/ts2fable#285]

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/52852625-1e7c7e80-3154-11e9-9e1e-0596fa13659c.png)
cc @MangelMaxime

**Comment by MangelMaxime** [comment]
I thought it was the case.

If you make the CI run `WebApp.Publish` when master receives a commit it will/should publish a new version.

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/52857120-28f14500-3161-11e9-88d9-09c6ea8055da.png)
Is npm token expired ?

I really have no idea how can i configure npm token and github token safely in this repository.....

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @ctaggart 

Can one of you make me collaborator of ts2fable npm package? So I can generate a new npm token.

@humhei  I will also change the [following lines](https://github.com/fable-compiler/ts2fable/blob/master/common.fsx#L358-L367) in order to us my github account.

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/52858214-7de28a80-3164-11e9-8cd0-012070273fd6.png)


The main point is i  cannot configure appveyor environments
![image](https://user-images.githubusercontent.com/25994449/52858345-cdc15180-3164-11e9-9ac5-642a4c34ff75.png)

Thanks @MangelMaxime

**Comment by MangelMaxime** [comment]
Ok, well I can manage the environments but can't give you the permission Cameron is the one who created the repo originally I think.

**Comment by ctaggart** [comment]
>I really have no idea how can i configure npm token and github token(Which is used to publish ts2fable online version) safely in this repository.....

@humhei, do you use the email listed in https://github.com/humhei to log in to AppVeyor?

**Comment by ctaggart** [comment]
I can add you here: https://ci.appveyor.com/account/fable-compiler/team

The environment variable you want to set is here:
https://ci.appveyor.com/project/fable-compiler/ts2fable/settings/environment

![image](https://user-images.githubusercontent.com/80104/52859928-10027880-30fc-11e9-92a0-b0517f8ca1b7.png)

**Comment by humhei** [comment]
> @humhei, do you use the email listed in https://github.com/humhei to log in to AppVeyor?
@ctaggart 
Yes my email is humhei@outlook.com

Please add me

**Comment by ctaggart** [comment]
@humhei, just added you. The invite should be in your email inbox.

**Comment by humhei** [comment]
@ctaggart  
Thanks very much.


![image](https://user-images.githubusercontent.com/25994449/53063389-e207a480-34fe-11e9-85f8-57efb72b8ab5.png)
Now the online version will be auto updated when commit is merged
cc @0x53A
