### ISSUE TITLE
Fable.Import from multiple files

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/ts2fable#29]
As mentioned in one of my previous comments. It would be great to import from multiple files. 

As people are moving more towards `Typescript`, it is becoming easier to use libraries because of `index.d.ts`. And authors are also using this to keep `d.ts` file small. So, for `typescript` it is non-issue. But it is for us as we are converting things from them. I have created gist for `Flatpickr` latest version `4.x` at https://gist.github.com/kunjee17/761f3ffeabd6c9abc04e89a148b8a67c . It do have `index.d.ts` file but as you can see it only have exposing gobal variables. And complete type definition at `@types/flatpickr` is still at 3.x version. 

It would be great if can parse whole `index.d.ts` instead of only file. 

Hope I make sense.

**Comment by alfonsogarciacaro** [comment]
I don't know if TS type checker gives you info of all exposed types from references in `index.d.ts`. If that's not the case, the other option would be to just find all `d.ts` files in the folder (and subfolders) and translate them. It should be no problem to include several .fs files in the distributed .dll, but it may be tricky to [infer the proper import path](https://github.com/fable-compiler/ts2fable/issues/21#issuecomment-341410711) from nested files...

**Comment by kunjee17** [comment]
@alfonsogarciacaro the problem is index.d.ts is not importing from other d.ts file. But normal ts file. So, searching from file may not be that much helpful.

**Comment by ctaggart** [comment]
@kunjee17 I made it so you can specify multiple .ts files as input. I don't yet know how to deal with imports and namespaces. Please try it out though. `yarn add global ts2fable` should get you the latest with this added. https://github.com/fable-compiler/ts2fable/pull/80

**Comment by kunjee17** [comment]
@ctaggart I ll try it out. And let you know as soon as possible... Thanks...

**Comment by kunjee17** [comment]
I tried latest. But I guess npm is not updated yet. I am still having 0.2.0 version there.

**Comment by ctaggart** [comment]
yarn global add ts2fable@next

**Comment by ctaggart** [comment]
Also try it with regular .ts files.

**Comment by kunjee17** [comment]
@ctaggart cool. I ll give a shot. I ll be travelling so either I ll try it now or it may take little time till weekend. Will try to get back to you as soon as possible.

**Comment by ctaggart** [comment]
I'm marking this complete for 0.3.0. It is more experimental. It "works" but namesapces fixes are not taken into account. I'll address that after 0.3.0.
