### ISSUE TITLE
ts2fable type provider

### ISSUE THREAD

**Issue by beshanoe** [fable-compiler/ts2fable#294]
Hi! I'm quite new to the F# and Fable, in particular, so maybe this question might seem silly, but is it possible to write ts2fable in form of F# type provider? It's weird not using this unique language function for providing typescript types to F# app. I would like to know if there are any limitations of Fable or F# preventing this. Thanks

**Comment by alfonsogarciacaro** [comment]
Well, if it's possible it will certainly not be easy. There are two main obstacles:

- ts2fable is actually a node.js app with communicates with the typescript compiler. Type providers run on dotnet, so you'd have to find a way to communicate between processes.
- Type providers have limitations. IIRC they cannot generate generic types, for example.

**Comment by beshanoe** [comment]
Thanks for the response! Yeah, even if there was purely dotnet type provider, generics is pretty much important feature
