### ISSUE TITLE
To option or not to option

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/ts2fable#302]
All optional properties in TS definitions are, in general, translated to `option`-wrapped types in F#.

This is a good general rule, and makes perfect sense for get-only properties. The F# developer gets an object with `option` members which may be null/undefined, and is required to pattern match etc.

However, for set-only properties, e.g. simple "property bags" used in many constructors, AFAIK it's better to remove the `option` wrapping, because generally (unless documented otherwise) they should never be set to `null`. You create an empty object and set the properties you need, so you either set them to a real (non-null) value or you don't set them at all.

For get-set properties there is often no perfect solution, but the safest thing is of course to keep them `option`-wrapped and live with the extra inconvenience that you have to wrap them in `Some` when setting.

Is my understanding correct, and am I right in that optional properties on set-only types ("property bags") should in general *not* be wrapped in option? I have been removing `option` from such types up until now, but it could conceivably cause problems if a set-only type starts being used in get contexts. (One could always duplicate the type definition and have option wrappers for one of them, but that's not ideal either.)

**Comment by MangelMaxime** [comment]
It's that in the past we were marking all these "property bars" with `option`.

Since Fable 2, we re-considered and consider it ok to not mark them using `option` in order to make the code less verbose when doing:

```fs
jsOption<Config>(fun o ->
    o.oldStyle <- Some myValue // With option
    o.newStyle <- myValue // Without option
```

**Comment by cmeeren** [comment]
Thanks! But that's only for set-only objects, right? If they are returned from some API method, then they should still be `option`, as I mentioned, right?

**Comment by MangelMaxime** [comment]
> then they should still be option, as I mentioned?

Yes, like that the user is forced to handle `None` and so the compiler can help the user write "safe" code.

**Comment by cmeeren** [comment]
Thanks!
