### ISSUE TITLE
Emits default constructor when TS does not contain a constructor

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/ts2fable#305]
The Electron bindings contain the following classes:

```ts
class BrowserWindowProxy {
  // no constructors
  // ... (other members)
}

class BrowserWindow {
  constructor(options?: BrowserWindowConstructorOptions);
  // ... (other members)  
}
```

ts2fable emits static constructor methods for both of these. Should it? The [`BrowserWindowProxy` documentation](https://electronjs.org/docs/api/browser-window-proxy) says that it is only returned from other API methods (i.e., it can/should not be constructed directly – all classes that can be constructed have documented constructors).

**Comment by cmeeren** [comment]
Compare with the `Menu` type which [has a documented default constructor](https://electronjs.org/docs/api/menu) and where the typings also have an explicit default constructor:

```ts
class Menu {
  constructor();
  // ... (other members)
}
```

**Comment by 0x53A** [comment]
afaik Typescript works like C# - if there is no constructor at all, it emits a parameterless default ctor.

If you don't want the ctor to be accesible, you can manually declare a private ctor.

You can test this out in the playground: https://www.typescriptlang.org/play/index.html

This compiles:

```ts
class BrowserWindowProxy {

}

var b = new BrowserWindowProxy();
```

**Comment by cmeeren** [comment]
Ok, so there's simply no way for ts2fable to know for sure whether a TS class should be directly instantiable or not? (C.f. the examples I posted.)

**Comment by 0x53A** [comment]
> so there's simply no way for ts2fable to know for sure whether a TS class should be directly instantiable or not?

There is, add a private parameterless ctor. Otherwise. no.


> Might it be the case that .d.ts files commonly list default constructors explicitly where relevant, so that this could be a useful heuristic for ts2fable?

I don't think so. I've seen the pattern of private ctor in babylonjs, so I think ts2fable should just faithfully translate the ts to f# as far as possible.

**Comment by cmeeren** [comment]
Thanks, closing this then.
