### ISSUE TITLE
Conversion error for heremaps

### ISSUE THREAD

**Issue by sandeep-eroad** [fable-compiler/ts2fable#332]
heremaps ts conversion 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/heremaps

results in following error
```
unsupported Statement kind: 249
```

**Comment by MangelMaxime** [comment]
Hello, can you please using [https://fable.io/ts2fable/](https://fable.io/ts2fable/) as a workaround?

**Comment by sandeep-eroad** [comment]
Thanks Maxime, that works. I'll leave it to you to close the ticket.

**Comment by humhei** [comment]
should be fixed in 0.7.1
