### ISSUE TITLE
Issue using the types from tmi.js

### ISSUE THREAD

**Issue by 7sharp9** [fable-compiler/ts2fable#333]
Given the tmi.js npm/types:  

```bash
npm I tmi.js
npm i -D @types/tmi.js                                                                                                                                         
```

And invoking via:
```
ts2fable node_modules/@types/tmi.js/index.d.ts  src/tmi.fs
```

```bash
master  ✱
ts2fable 0.7.0
export node_modules/@types/tmi.js/index.d.ts
unsupported Statement kind: 254
Error: Cannot read property 'kind' of undefined
```

**Comment by MangelMaxime** [comment]
The web version of the tool available [here](fable.io/ts2fable) seems to work as expected. 

Can you please try it as a workaround?

**Comment by 7sharp9** [comment]
yeah that works, perhaps a cli tool that just uses the on-line one could be nice.

**Comment by MangelMaxime** [comment]
Well in theory, the cli and online tool are just client of the ts2fable library.

The benefit of the cli is that it can works on multiple files at the same time. I suspect we have a bug in the release process because the CLI is 0.7.0 while the online application say 0.8.0.

**Comment by humhei** [comment]
They should be the same code base. 
But the the files in previous dist folder is very odd 
![image](https://user-images.githubusercontent.com/25994449/75846988-e0163800-5e18-11ea-951e-a356b4618540.png)
I think the build script to pack ts2fable to dist folder is the case
