### ISSUE TITLE
CLI and WebApp versions are out of sync

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/ts2fable#337]
Since the beginning of February, we are seeing an increase of issues like 

```
unsupported Statement kind: 254
Error: Cannot read property 'kind' of undefined
```

Example: #333 

It looks like the CLI is in version 0.7.0 and the WebApp 0.8.0. 

@humhei Do you have an idea why they are out of sync?

**Comment by humhei** [comment]
They should be the same code base. 
But the the files in previous dist folder is very odd 
![image](https://user-images.githubusercontent.com/25994449/75846988-e0163800-5e18-11ea-951e-a356b4618540.png)
I think the build script to pack ts2fable to dist folder is the case

**Comment by humhei** [comment]
Still not fixed,
Maybe this is because the typescript dependecy is auto upgraded from typescript@3.7.4 to 3.8.3
change "typescript": "^3.7.4" to "typescript": "3.7.4" may fixed it

**Comment by humhei** [comment]
Should be fixed in 0.7.1
the different version of typescript case this problem

**Comment by humhei** [comment]
> It looks like the CLI is in version 0.7.0 and the WebApp 0.8.0.

This is by purpose,
Because webApp updated every commit is merged
So we set the version to next version

**Comment by MangelMaxime** [comment]
Do you mean that the WebApp is kind of always updated to vNext?

**Comment by MangelMaxime** [comment]
And thank you for taking a look at the problem :)
