### ISSUE TITLE
How to convert interface types that inherit from System.Exception?

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/ts2fable#341]
```
type Error = System.Exception
```
...

```
    /// A type that filesystem providers should use to signal errors.
    /// 
    /// This class has factory methods for common error-cases, like `FileNotFound` when
    /// a file or folder doesn't exist, use them like so: `throw vscode.FileSystemError.FileNotFound(someUri);`
    type [<AllowNullLiteral>] FileSystemError =
        inherit Error

    /// A type that filesystem providers should use to signal errors.
    /// 
    /// This class has factory methods for common error-cases, like `FileNotFound` when
    /// a file or folder doesn't exist, use them like so: `throw vscode.FileSystemError.FileNotFound(someUri);`
    type [<AllowNullLiteral>] FileSystemErrorStatic =
        /// <summary>Create an error to signal that a file or folder wasn't found.</summary>
        /// <param name="messageOrUri">Message or uri.</param>
```

The problem here is that `Error` is not an interface type and `ts2fable` is generating outright erroneous code. There is a mismatch here between TS which has a structural type system and F# which has a nominal one.

What would be the best thing to do here?

**Comment by mrakgr** [comment]
```
interface Error {
    stack?: string;
}
```

It seems that in TS, the `Error` is just this. I forgot to note, but these bindings are for VSCode's API.

**Comment by MangelMaxime** [comment]
By looking, at the discussions about the change made in Fable.Core 3 it seems we still haven't resolved the Error problem yet.

A solution, for now, is to use this [package](https://github.com/0x53A/fable-tsinterop-ex). Which add back a few of the type we removed from Fable.Core 3. And for example, it does have the Error type. [Source code](https://github.com/0x53A/fable-tsinterop-ex/blob/master/src/Fable.TSInterop.Ex/Fable.Core.JS.fs#L336-L338).

You can easier make it a dependency of your project or copy the relevant code that you need.

**Comment by mrakgr** [comment]
Thanks.
