### ISSUE TITLE
map simple TypeLiteral types

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#35]
``` ts
	type Point = {
		x: number;
		y: number;
	}
```
from c:\Users\camer\fs\ts2fable\node_modules\@types\electron\index.d.ts

![image](https://user-images.githubusercontent.com/80104/32297360-d5e42234-bf46-11e7-81e9-713de7c6935e.png)

**Comment by ctaggart** [comment]
typescript.d.ts has several examples. I'm not sure how I would map this one.
``` ts
    interface Iterator<T> {
        next(): {
            value: T;
            done: false;
        } | {
            value: never;
            done: true;
        };
    }
```
current mapped as 
``` fs
member __.validateLocaleAndSetLanguage(locale: string, sys: obj, ?errors: Push<Diagnostic>): unit = jsNative
```

How should it be mapped?

**Comment by alfonsogarciacaro** [comment]
This is really complicated to translate to F#. We could use `U2` but the two cases are just structural interfaces in TypeScript so there won't be an easy way to do pattern matching against the result in F#. Currently Fable translates pattern matching with erased unions as [type testing with the generic parameters](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0Alet%20foo()%3A%20U2%3Cstring%2C%20float%3E%20%3D%0A%20%20!%5E%22foo%22%0A%20%20%0Alet%20test()%20%3D%0A%20%20%20%20match%20foo()%20with%0A%20%20%20%20%7C%20U2.Case1%20s%20-%3E%20printfn%20%22STRING%20%25s%22%20s%0A%20%20%20%20%7C%20U2.Case2%20i%20-%3E%20printfn%20%22NUMBER%20%25f%22%20i%0A%20%20%20%20%0Atest()) but obviously this won't work in imaginative cases like this one :wink:

As here both cases have the same properties, just for this specifc case I would use something like:

```fsharp

type IteratorResult<'T> =
   abstract value: 'T option
   abstract done: bool

type [<AllowNullLiteral>] Iterator<'T> =
   abstract next: unit -> IteratorResult<'T>
```

**Comment by alfonsogarciacaro** [comment]
Regarding the TypeLiteral types mentioned in the title, I guess you mean `done: false` in this case. I'm afraid there's no other option in F# than using directly the type (`bool` in this case) but maybe there's another solution 🤔

**Comment by ctaggart** [comment]
I'm going to try to solve the simple case for Electron for the 0.2.0 release. It looks like there are several variations that involve TypeLiterals. We may be able to pick up additional variations in the future.

**Comment by ctaggart** [comment]
The TypeLiterals I wanted to cover for now are in #121.
