### ISSUE TITLE
Use Array instead of ResizeArray with ParamArrayAttribute

### ISSUE THREAD

**Issue by Booksbaum** [fable-compiler/ts2fable#362]
```typescript
declare function f(...args: string[]): void;
```
gets converted into
```fsharp
type [<AllowNullLiteral>] IExports =
    abstract f: [<ParamArray>] args: ResizeArray<string> -> unit
```

This is correct: Typescript array gets converted into F# ResizeArray.  
But: It's most likely used to manually pass in (a variable number of) arguments. But in F# that's only possible with an array, not ResizeArray:
```fsharp
f("A", "B")
```
> The member or object constructor 'f' takes 1 argument(s) but is here given 2. The required signature is 'abstract member IExports.f : [<ParamArray>] args:ResizeArray<string> -> unit'.

I think it's reasonable to emit `array` instead of `ResizeArray` for `...`:
```fsharp
type [<AllowNullLiteral>] IExports =
    abstract f: [<ParamArray>] args: string[] -> unit
```

Yes, `ResizeArray` and `array` have different behaviour, but most of the time it's used to directly write all parameters, while a dedicated list is only rarely used.  
-> `array` is far more convenient

**Comment by alfonsogarciacaro** [comment]
Yes, it's tricky to decide if JS array should be represented with F# array (fixed size but better syntax, sometimes conflicts with Fable typed arrays conversion) or ResizeArray (variable size but worse syntax). In this case because of the attribute it does look more reasonable to use array.

Not sure if it can be used here, but just for reference Fable.Core has ParamSeq which will spread any seq parameter (including list) no only arrays. But obviously you cannot use the same syntax as ParamArray with multiple arguments.

**Comment by Booksbaum** [comment]
There doesn't seem to be a difference between `ParamArray` and `ParamSeq`: [Fable source](https://github.com/fable-compiler/Fable/blob/nagareyama/src/Fable.Transforms/FSharp2Fable.Util.fs#L492) and [Fable repl test](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQokUAygJ4DOALmALYEFVniwVQC8BU3UA2gDwBxJMARwkACgBEAMykBKAHwBdLj2pwqASwDGUWnQRgsUGQEYoEiHAMAuKNSxaIAcwA0ffgAU4WGwEEsPzIVKF8XCnsAJTAKLQAvMEDg-kdnF0V5ewBXCC0qDigAKwoAOU0tADc8fB5PYVFxaTklVVr1Kgq9A1ojExkAJktrOwcqJ1cPAR8-WmS4EOUwrAj7NNdeZSyoXPzCkvLtarVuAQaxSVkFFROxrv1DY1MAZmGbMDXx9KnvXwCghahcKRMYTFxQJBaajbXYFdjFMoVY7tU5CEQXZrXNp1DTabqPfoAFjeo3W7k8M3+wSBKxBZIcYAAjjC8nCEYcqjVbmd0U0rq1brjdA9ek8ZABWEkfUHfCl-WgAGShVBpqygMTiiXmZFSX1cmRyrP2iKONTqPMalxaNxRdzxIr6pgAbFLPmCfpTFcrVXS9S5Niy9vCDkizTwLRj+TacZ17T1HTIAOyumWTOWzJXUH1u9IQ5WBtkh03ctGWzEC21C-Gi-oADhTZI98szKqWwJzrgZzMNQfZoYY+BQBQAJpo4IVeFJ-FIANxQKQAIVn8-QUjaBBgFFQ5mknu1AFoNQkkgCyFIPEetaeJKPOvJ5AQAPSP1jbszSaceRfnlcKDdbwZd3lA9tR-W9xwAH0UKAW1QKhgG1B98E3bcBiA2YQNPKAQHlCgfynfCly-VckJQmRnnQqkFn3FswLHJDn1fciP0I-CSP-bdCUouZT33EgmTozooCgmDlTg4B+OZJ8XzIiiCK-IjfyQjiJW4ltD1iY9QIvTSr2CG96IYmSAK4+T50UqR2OQgCnTU5V920qBwOE6DYPgxDpKY8UWIUti-2s7dEzs6gaOVQS4CMpjbLM79iP8sja2Cqg+IEjxnJEtyJKZSKyOiz9zL85T8CAA&html=DwCwLgtgNgfAsAKEaApgQwCbwQAjz4CFMNHcMABwFoUBHAVwEsA3AXgHIBhAewDswU-KgBUAnhRTscAYz4D+HAQA8wAenDQA3DJBoATgGdiremABmVABztswdeiyJkAI24ZR2fAQPS9jCmCe+KqqZGCUBgBcIQDucQB0YOIoPn4BUGi8AObx3HpZqhQZogD8AMSyGCiqAOIAmgBqMRhZSlkAMllQWQCcEACCAEIAsv0AYjX9IFkA6jEA0nWcAKwAogAiAPIAqv3CAFaTm3X9AAyM-RgAEikoAIpmANZoAEp3AHLcnABs-VAAkll3gAWfrcF7DYZ3frOZxjVbCMYGQYvcZrfr9GL9R5mdbrLKcADUhJe2wAUqtBgBmIZ1JRKeaDR5KPzzXbArKDSwXfqiHqDf4ARkFZIg-36gv6emGqzQQwAXiAqBNlhh3lSMAAtZynaGAwb0GrtdYbbYAZX+g36-2B0juBltIBeFD+60egpqFzGL0e3DQmwo3Cyq1W8zFUxmTH6dRm+3o4sQXgARPQjDgDGA-NIwEnNIn8GZ6Lxs4w+DgzAAKXhoIgAGhw8Ub+iyBgAlDgAN75rx4KDEHB6FI4Vg4AAGABIO9WiABfSJjvO4Ht4GIgRh9nAV5sGeJ97JgEA4GA4U7trtL5deQcGHCEkfb+KBigV1uLy896+3ke5nC57s9md-y8WReAMbg+13IMK2vV9-0Ai8cBCcsKyTYQUhzesk36JNMMGHDf04JNYIQuxUn8QJkFUVx3GwSiNFgRAgA&css=Q) (repl uses a older version -> `ParamList` instead of `ParamSeq`, but seems to have same code & behaviour as current fable version)

So no really any reason not to use `ParamArray`. Maybe with the exception that `ParamArray` usually marks a location you can use a variable number of parameters -- which doesn't work with anything other than array. So it might be a bit confusing at first when it's used without an array.


But here it's about intention and convenience: The source function is designed to be used with a variable number of parameters. It only makes sense to translate that into F# too.
