### ISSUE TITLE
Invalid function name when parameter with string literal type contains space

### ISSUE THREAD

**Issue by Booksbaum** [fable-compiler/ts2fable#374]
(simplified from [mocha](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7a0d9c019f2b48b36b88691247870e6885b97a02/types/mocha/index.d.ts#L1625))
```typescript
interface Runner {
    on(event: "Hello World"): void;
}
```
gets converted into
```fsharp
type [<AllowNullLiteral>] Runner =
    [<Emit "$0.on('Hello World')">] abstract on_Hello World: unit -> unit
```

> error FS0010: Unexpected identifier in member definition. Expected ':' or other token.

Space in "Hello World" is kept.

Should be double backticks (` ``on_Hello World`` `) or underscore (`on_Hello_World`). Not sure which one is preferable: We already use underscore to connect name with string literal, but in other places, if there's an invalid char, double backticks are used. And: error happens for all invalid identifier characters -- which might make for strange function names when replaced with underscore.   
-> I think double backticks are better. But that's strange in combination with function name (`on_Hello World`) -- maybe remove backtick between `on` und string? But that introduces strange namings for strings without invalid chars...

**Comment by alfonsogarciacaro** [comment]
Maybe making it two-step? First replacing spaces with underscore, then checking if the identifier still has invalid characters and in that case use the double ticks?

**Comment by Booksbaum** [comment]
Seems reasonable. But then again it's the issue: what to do with multiple spaces? combine into one underscore or one underscore for each space? ... ah ... formatting stuff ....

I'm going to take the easy route: one underscore per space
