### ISSUE TITLE
map mapped types

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#44]
c:\Users\camer\fs\ts2fable\node_modules\@types\react\index.d.ts
``` ts
    interface Validator<T> {
        (object: T, key: string, componentName: string, ...rest: any[]): Error | null;
    }
```

0.1.23 is mapping it as:
``` fs
and [<AllowNullLiteral>] ValidationMap<'T> =
    obj
```

0.2.0 develop is mapping it as :-)
``` fs
    type ValidationMap<'T> =
        TODO
```

How should it be mapped? This is SyntaxKind.MappedType is TypeScript. cc @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Weird, doesn't ts2fable use `Invoke` here?

```fsharp
type ValidationMap<'T> =
  [<Emit("$0($1...)")>]
  abstract Invoke: object: 'T * key: string * componentName: string * [<ParamArray>] rest: obj[] -> Exception option
```

**Comment by ctaggart** [comment]
I think this was fixed for 0.2.0 final.

**Comment by humhei** [comment]
This is still not fixed
Should we reopen this?

**Comment by humhei** [comment]
```fsharp
type ValidationMap<'T> =
    obj
```

**Comment by humhei** [comment]
https://github.com/fable-compiler/ts2fable-exports/blob/master/React.fs#L2579

**Comment by humhei** [comment]
They are different issues 😳 
I will open a new issue
Current react version 's `ValidationMap `
``` typescript
type ValidationMap<T> = {[K in keyof T]?: Validator<T> };

```
