### ISSUE TITLE
Generate constructor

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/ts2fable#59]
@ctaggart When using the [ws.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts), [this lines](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts#L41-L42) have no equivalent generated by ts2fable.

Do you know if we can generate something for them ?

Also, @alfonsogarciacaro what should we use to translate them ?
For an example, the SocketIo use something [like this](https://github.com/fable-compiler/fable-import/blob/master/SocketIo/Fable.Import.SocketIo.fs#L58-L63).
And it access it we use [this import](https://github.com/fable-compiler/fable-import/blob/master/SocketIo/Fable.Import.SocketIo.fs#L148-L149)

I didn't test the code with latest version of Fable but I believe this should work.

**Comment by ctaggart** [comment]
Constructors are mapper to a Create method on an interface with "Static" suffix. That didn't happen?

**Comment by MangelMaxime** [comment]
I just checked, and no that didn't happen here.

**Comment by enricosada** [comment]
Adding myself, because was my issue initially.

i rerun `ts2fable` and now i have 

```fsharp
type [<AllowNullLiteral>] WebSocketStatic =
    [<Emit "new $0($1...)">] abstract Create: address: string * ?options: WebSocket -> WebSocket
    [<Emit "new $0($1...)">] abstract Create: address: string * ?protocols: U2<string, ResizeArray<string>> * ?options: WebSocket -> WebSocket
```

i'll send a pr to https://github.com/Prolucid/fable-import-ws

**Comment by MangelMaxime** [comment]
Ah, ok so perhaps I was using the wrong version of ts2fable.

Seems like I can't do `npm uninstall -g ts2fable` always fun. We can probably close it so.

**Comment by MangelMaxime** [comment]
Ok I fixed my environment. Always fun to use windows :)

And indeed the latest version of ts2fable generate the `WebSocketStatic` for me too. :)
