### ISSUE TITLE
Parse Documentation Comments from `d.ts` Declaration Files

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/ts2fable#6]
Follow up of https://github.com/fable-compiler/Fable/issues/325

**Comment by ctaggart** [comment]
From #1 [comment](https://github.com/fable-compiler/ts2fable/issues/1#issue-217374509):
> Use Typescript type checker: The current ts2fable version just does syntax parsing, the info provided from the type checker would make it easier to check inheritance, etc. It also makes it easier to translate the comments.

From [Using the Type Checker](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) example, it looks like you have to `ts.createProgram` to `getTypeChecker`.

**Comment by alfonsogarciacaro** [comment]
Yes, another option is to use [ts-simple-ast](https://dsherret.github.io/ts-simple-ast/) which apparently removes the dichotomy between Typescript syntax parser and type checker ([example](https://github.com/fable-compiler/ts2fable/blob/750d0e1f0046051a551ebf826e096610a335bca6/src/parsers.ts#L116)).

**Comment by ctaggart** [comment]
Fixed by #66. At least a good first pass. :-)
