### ISSUE TITLE
Files in NPM package contain Windows line endings

### ISSUE THREAD

**Issue by inosik** [fable-compiler/ts2fable#65]
I just tried adding ts2fable globally via Yarn, but I can't execute it on macOS:

```
$ ts2fable 
env: node\r: No such file or directory
```

I don't get this error with NPM.

This looks more like an issue with Yarn though, because it obviously doesn't normalize line endings. Should I rather open an issue there?

**Comment by ctaggart** [comment]
I thinks so. Not really sure. That line is being prepended here. https://github.com/fable-compiler/ts2fable/blob/master/build.ps1#L36
May be there is a better way to add it.

**Comment by ctaggart** [comment]
@inosik can you install/update to the latest using yarn and try it out? It should be fixed as of build 42. https://ci.appveyor.com/project/fable-compiler/ts2fable/build/42

```
yarn global add ts2fable@next
```

**Comment by inosik** [comment]
The latest version works on macOS again, thanks!

**Comment by alfonsogarciacaro** [comment]
Yes, I also had this problem. Files with the shebang `#!/usr/bin/env node` touched by Windows won't work in UNIX (at least on macOS). I think it has to do with the BOM, not only the line endings. In any case, I'm glad to see you fixed it @ctaggart, thank you!

> npm actually creates a `.cmd` version of the executable when installing a package.
