### ISSUE TITLE
yarn global add ts2fable@next does not execute correctly

### ISSUE THREAD

**Issue by mike-morr** [fable-compiler/ts2fable#78]
yarn global add ts2fable@next
ts2fable .\node_modules\chalk\types\index.d.ts .\chalk.fs

results in:

![image](https://user-images.githubusercontent.com/6625993/32738568-9ef9bb0e-c85a-11e7-8945-53d3d5bfc8dd.png)

I am on Windows 10 if it helps.

**Comment by ctaggart** [comment]
@mike-morr, please uninstall the version from npm and use the one installed via yarn. If you type `which ts2fable` it should show it coming from a yarn folder.

```
C:\Users\camer\fs\ts2fable\src [negative-enum-cases]> yarn global list
yarn global v1.3.2
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info "babel-cli@6.26.0" has binaries:
   - babel-doctor
   - babel
   - babel-node
   - babel-external-helpers
info "mocha@4.0.1" has binaries:
   - mocha
   - _mocha
info "ts2fable@0.3.0-build.45" has binaries:
   - ts2fable
Done in 1.03s.
C:\Users\camer\fs\ts2fable\src [negative-enum-cases]> which ts2fable
/c/Users/camer/AppData/Local/yarn/bin/ts2fable
```

**Comment by ctaggart** [comment]
@mike-morr, I'm closing this, but please let me know if your issue is indeed resolved.

**Comment by mike-morr** [comment]
@ctaggart That fixed it!  Thank you!!
