### ISSUE TITLE
Use prettier

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/ts2fable#8]
Any objection to adding [prettier](https://github.com/prettier/prettier) to this repo?

**Comment by alfonsogarciacaro** [comment]
Not from my side, looks like a useful tool 😄 It may depend on whether we move to Typescript or not, but now it's possible to use type checking with JsDocs so we can keep just using JS.

**Comment by ctaggart** [comment]
This issue can be closed. With #19, we have switched to using Fable to build ts2fable in the development branch.

**Comment by alfonsogarciacaro** [comment]
Good point! Thank you @ctaggart :+1:
