### ISSUE TITLE
add readonly property support

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#81]
chalk is a good test case

**Comment by alfonsogarciacaro** [comment]
Yes, that would be very nice. I guess just removing `with get, set` for readonly properties should be enough :)

**Comment by ctaggart** [comment]
I was just going to remove the `set`. Any advantages to removing all of it?

**Comment by alfonsogarciacaro** [comment]
Hmm, I guess the file may look a bit cleaner as `with get` is the default for F# interface properties. But it's also fine if you prefer to keep it :)

**Comment by ctaggart** [comment]
``` ts
readonly reset: this;
```
![image](https://user-images.githubusercontent.com/80104/32864885-947c1e9c-ca3f-11e7-8f63-50cad2356655.png)
