### ISSUE TITLE
Crashing the ionide with generated import file

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/ts2fable#82]
I was facing weird issue when I tried 0.2.0 ts2fable to generate Servicestack-client imports. While old generated imports are very much working new one were not. And also they are crashing the whole ionide and I have no idea why. I created gist of all files at <https://gist.github.com/kunjee17/7cf9fa9de09c3653cdb0af98c9722801> . 

It would be great if some one else can give a shot and see if that breaks things. And then we can try to find out issues in generated code. 

PS: don't forget to add file in fsproj. After that it will get messy.

**Comment by ctaggart** [comment]
@kunjee17, please test with ts2fable@next. There has been a lot of changes since 0.2.0.

**Comment by ctaggart** [comment]
May be this is a Fable 1.3 problem:
@LambdaFactory https://twitter.com/k_cieslak/status/930936153850736640
@alfonsogarciacaro

**Comment by ctaggart** [comment]
btw @LambdaFactory, if you use ts2fable@next to import electron.d.ts, you get a lot of API documentation comments. A 0.3.0 release should be as soon as one more issue is fixed.

**Comment by kunjee17** [comment]
@ctaggart crashing seems to be stopped. I have updated the gist. But I didn't get the `JavaScriptClientStatic.Create` part. Is it replacement for constructor in TypeScript?

**Comment by ctaggart** [comment]
Yes, a constructor becomes a static `Create` method. The static method are put in a new interface the `Static` appended to the name.

**Comment by kunjee17** [comment]
@ctaggart sorry for dumb question. But how to use Static type in above case. Means that is also abstract class. So, should I try `createEmpty` or `jsoption` for it. I tried jsoptions that did't work. need to check create empty though. 

Below is simple reference code 

```fsharp
type [<AllowNullLiteral>] IExports =
    abstract HelloResponse: HelloResponseStatic
    abstract Hello: HelloStatic

type [<AllowNullLiteral>] IReturn<'T> =
    abstract createResponse: unit -> 'T

type [<AllowNullLiteral>] IReturnVoid =
    abstract createResponse: unit -> unit

type [<AllowNullLiteral>] HelloResponse =
    abstract result: string with get, set

type [<AllowNullLiteral>] HelloResponseStatic =
    [<Emit "new $0($1...)">] abstract Create: unit -> HelloResponse

type [<AllowNullLiteral>] Hello =
    inherit IReturn<HelloResponse>
    abstract name: string with get, set
    abstract createResponse: unit -> unit
    abstract getTypeName: unit -> unit

type [<AllowNullLiteral>] HelloStatic =
    [<Emit "new $0($1...)">] abstract Create: unit -> Hello

```

So, how to create Hello out of HelloStatic?

PS: On side note. In `Hello` type `createResponse` type is coming wrong. It should be `HelloResponse`. For reference below is TypeScript code. 

```
export interface IReturn<T>
{
    createResponse() : T;
}

export interface IReturnVoid
{
    createResponse() : void;
}

export class HelloResponse
{
    result: string;
}

// @Route("/hello")
// @Route("/hello/{Name}")
export class Hello implements IReturn<HelloResponse>
{
    name: string;
    createResponse() { return new HelloResponse(); }
    getTypeName() { return "Hello"; }
}
```

I am using latest `0.4` version of ts2fable. If you want I can file another issue for same.

cc/ @MangelMaxime

**Comment by alfonsogarciacaro** [comment]
@kunjee17 `HelloResponseStatic` (as well as the other -Static interfaces) should be exposed  in the `IExports` object.

**Comment by kunjee17** [comment]
@alfonsogarciacaro oh ok. So, I can created empty of IExport and access them all?

**Comment by alfonsogarciacaro** [comment]
The `IExports` object should already be exposed somewhere. I'm not sure how it works in latest ts2fable, do you have a link for the bindings you're using?

**Comment by kunjee17** [comment]
@alfonsogarciacaro not as of now. I am just trying things as ts2fable come out. I am keeping old definition for now. But I surely give a try. Only thing is I don't know how to use it.

**Comment by ctaggart** [comment]
@kunjee17 It is better to create new issues.
