### ISSUE TITLE
use yargs

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#87]
It would be good to use an arguments library. I'm currently thinking http://yargs.js.org/. It has a @types/yargs. https://github.com/yargs/yargs

Another stage could be full configuration through something like https://github.com/indexzero/nconf. It uses yargs for its command line processing

**Comment by alfonsogarciacaro** [comment]
Looks nice! Fable 0.7 used [command-line-args](https://www.npmjs.com/package/command-line-args) directly from TS. It can be [configured with a simple pojo object](https://github.com/fable-compiler/Fable/blob/b89698206160acae01fcf35ae889844ee97ff513/src/fable/Fable.Client.Node/ts/options.ts#L14-L41).

**Comment by ctaggart** [comment]
I got both command-line-args and yargs working with Fable. I like yargs a whole lot more. It is 100 times more popular in downloads stats and github stars.
