### ISSUE TITLE
ReadonlyArray to ResizeArray for params

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#88]
TypeScript 2.6 switch to ReadonlyArray's on a lot of their API. That is okay for return types, but any params should be turned into ResizeArray like before in order to be usable from Fable.

**Comment by alfonsogarciacaro** [comment]
`Fable` is not compatible `IReadOnlyList` yet (or `IReadOnlyCollection` not sure which one is a better fit her), but maybe it's a good idea to add it. The cast from `ResizeArray` would be automatic and the return types would work too.

**Comment by ctaggart** [comment]
#95 just replaces `ReadonlyArray` with `ResizeArray`. It is what was needed to upgrade TypeScript.
